networks:
  server-network:
    driver: bridge

services:
  backend:
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - server-network
    restart: always
    env_file:
      - .env

  db:
    container_name: db-container
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - server-network
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db: