networks:
  server-network:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - server-network
    restart: always
    env_file:
      - .env

  db:
    container_name: sushi_db_container
    image: postgres:16.4
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5010:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - server-network
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db: